#!/usr/bin/env sh
#
# Get colour output
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Program shortcuts
alias cz="chezmoi "
alias py="python "

# Editor shortcuts - these go into the main file
alias kconf="chezmoi edit ~/.config/kitty/kitty.conf && chezmoi apply "
alias aconf="nvim ~/.config/awesome/rc.lua && awesome -k; chezmoi re-add" # Check syntax is okay
alias zconf="chezmoi edit ~/.zshrc && chezmoi apply "
alias alconf="chezmoi edit ~/.aliases && chezmoi apply "
alias nconf="chezmoi edit ~/.config/nvim/init.vim && chezmoi apply "

# Editor shortcuts - these go into the folder
# Folders aren't tracked by chezmoi usually.
alias kdconf="nvim ~/.config/kitty/ && chezmoi re-add "
alias adconf="nvim ~/.config/awesome/ && chezmoi re-add "
alias tdconf="nvim ~/.config/awesome/themes && chezmoi re-add "
alias ndconf="nvim ~/.config/nvim/ && chezmoi re-add "

# Chezmoi shortcuts
alias cza="chezmoi git -- add "
alias czc="chezmoi git -- commit -v "
alias czp="chezmoi git -- push "
alias czs="chezmoi git -- status "
alias czd="chezmoi git -- diff "

# Git shortcuts
alias ga="git add "
alias gc="git commit -S -v "
alias gp="git push "
alias gs="git status "
alias gd="git diff "

# Avoid accidentally deleting files
alias mv="mv -i "
alias rm="rm -v "

# Copy things to x clipboard
alias xcopy="xclip -in -sel clip "
alias xcopyprim="xclip -in -sel prim "

# Create todo alias if I've actually got a file for it
[ -f ~/.todo ] && alias todo="cat ~/.todo"

# Source my own, non-tracked aliases
# shellcheck disable=SC1090,SC3046
[ -f ~/.my_aliases ] && source ~/.my_aliases
