#!/usr/bin/env sh
# Get my beloved nvim
export EDITOR=nvim

# Get cool paths
export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"

# Add colours to less
# From https://github.com/haxpor/sdl2-manpage#customize-man-pages-colors
export PAGER=less
export LESS_TERMCAP_mb=$'\e[01;31m' # begin blinking
export LESS_TERMCAP_md=$'\e[01;34m' # begin bold
export LESS_TERMCAP_me=$'\e[0m'     # end mode
export LESS_TERMCAP_se=$'\e[0m'     # end standout-mode
export LESS_TERMCAP_so=$'\e[0;35m'  # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\e[0m'     # end underline
export LESS_TERMCAP_us=$'\e[04;33m' # begin underline

# XDG stuff
export XDG_CONFIG_HOME="$HOME/.config"

# GRRRR
export BUNDLE_PATH=~/.gems

export GOPATH="$XDG_DATA_HOME"/go
